name: Notify Discord

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: ディスコードの通知を送信
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
              "embeds": [{
                "title": "${{ github.repository }} にpushされました!!",
                "description": "User: ${{ github.actor }}\nRepository: ${{ github.repository }}",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}",
                    "inline": false
                  }
                ]
              }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}